version: '3.7'

services:
  myedc:
    container_name: "myedc"
    build:
      context: ./
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      WEB_HTTP_PORT: 19191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 19193
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 19194
      WEB_HTTP_PROTOCOL_PATH: /protocol
      WEB_HTTP_PUBLIC_PORT: 19291
      WEB_HTTP_PUBLIC_PATH: /public
      WEB_HTTP_CONTROL_PORT: 19192
      WEB_HTTP_CONTROL_PATH: /control
      EDC_DSP_CALLBACK_ADDRESS: http://localhost/myedc/protocol
      EDC_API_AUTH_KEY: 5678
      EDC_PARTICIPANT_ID: YOUR_DAPS_ID
      EDC_OAUTH_TOKEN_URL: DAPS_TOKEN_URL
      EDC_OAUTH_CERTIFICATE_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_CLIENT_ID: YOUR_DAPS_ID
      EDC_OAUTH_PROVIDER_JWKS_URL: DAPS_JWKS_URL
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL
      EDC_IAM_TOKEN_SCOPE: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
      EDC_VAULT: /opt/connector/vault.properties
      EDC_KEYSTORE: /opt/connector/mykeystore.pfx
      EDC_KEYSTORE_PASSWORD: 123456
    env_file: "secrets/edc_ionos_secrets.txt"
    volumes:
      - ./resources/provider/mykeystore.pfx:/opt/connector/mykeystore.pfx
      - ./resources/provider/vault.properties:/opt/connector/vault.properties
    network_mode: "host"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/nginx.conf
    network_mode: "host"

secrets:
  GIT_AUTH_TOKEN:
    file: "secrets/git_auth_token.txt"